name = "RelationalEvents"
uuid = "bc9d85ce-390f-4ec2-a6bf-6f05cd1bda14"
authors = ["Jakob Hoffmann <jfb-hoffmann@hotmail.de> and contributors"]
version = "1.0.0-DEV"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
IntervalTrees = "524e6230-43b7-53ae-be76-1e9e4d08d11b"
SparseArrayKit = "a9a3c162-d163-4c15-8926-b8794fbefed2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[weakdeps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[extensions]
RelationalEventsDataFramesExt = "DataFrames"

[compat]
DataFrames = "1.6.1"
Dates = "1.11.0"
IntervalTrees = "1.1.0"
SparseArrayKit = "0.3.1"
StatsBase = "0.34.3"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
